/**
 * Textes d’information juridique (FR / ES / EN) pour modales pied de page.
 * Visent une mise en conformité de base avec la LFPDPPP (Mexique) pour un annuaire B2B
 * exploité par un particulier / petite structure — à faire valider par un conseil juridique local
 * si le volume de données ou l’activité augmente.
 */
import type { Language } from '../types';

export const LEGAL_PRIVACY_PARAGRAPHS: Record<Language, readonly string[]> = {
  fr: [
    'Le présent avis décrit comment sont traitées les données personnelles collectées via cet annuaire professionnel en ligne (ci-après le « Service »), exploité depuis le territoire mexicain. Il est rédigé en tenant compte de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) et des principes de licéité, consentement, information, finalité, loyauté, proportionnalité et responsabilité.',
    'Responsable du traitement : NextStep Services (ou l’entité désignée comme exploitant du Service), en qualité de responsable des données personnelles traitées dans le cadre de l’annuaire d’affaires francophone de Guadalajara. Pour toute question relative à ce document ou à vos droits, vous pouvez utiliser les coordonnées indiquées via le lien « Contact » en pied de page.',
    'Données collectées : identité (nom, prénom), coordonnées professionnelles (courriel, téléphone, messageries si renseignés), données relatives à l’entreprise (raison sociale, secteur, effectifs, localisation, site web, besoins ou centres d’intérêt professionnels tels que vous les saisissez), contenus que vous publiez (profil, annonces d’opportunités, commentaires le cas échéant), données de connexion et de sécurité (identifiant de compte, journaux techniques nécessaires à l’authentification et à la prévention des abus), ainsi que toute autre information que vous choisissez de fournir volontairement dans les formulaires.',
    'Finalités : (1) créer et afficher votre fiche dans l’annuaire selon les paramètres de visibilité que vous définissez ; (2) permettre la mise en relation entre membres ; (3) assurer le fonctionnement technique du Service (hébergement, sauvegarde, statistiques d’usage agrégées) ; (4) envoyer des communications liées au compte ou au Service lorsque nécessaire ; (5) respecter les obligations légales applicables au Mexique ; (6) modérer les contenus et prévenir la fraude ou les usages illicites.',
    'Transferts et sous-traitance : le Service peut s’appuyer sur des prestataires (hébergement, authentification, base de données, messagerie) situés au Mexique ou à l’étranger. Dans ce cas, des clauses contractuelles ou des mécanismes reconnus visent à protéger vos données conformément à la LFPDPPP. Les données peuvent transiter ou être stockées sur des serveurs situés hors du Mexique ; vous en êtes informé par le présent avis.',
    'Base du traitement : votre consentement lors de l’inscription ou de la mise à jour de votre profil, l’exécution des mesures précontractuelles ou du contrat de fourniture du Service, et le respect d’obligations légales le cas échéant. Les champs marqués comme obligatoires sont nécessaires à la fourniture du Service ; les champs optionnels le sont sur la base de votre consentement.',
    'Droits des personnes concernées (ARCO et autres) : conformément à la LFPDPPP, vous pouvez accéder, rectifier, annuler ou vous opposer au traitement de vos données, ou révoquer votre consentement pour les traitements qui y sont soumis, dans les formes et délais prévus par la loi. Vous pouvez également limiter l’usage ou la divulgation de vos données lorsque la loi l’autorise. Les demandes peuvent être adressées par le canal « Contact » ; une pièce d’identité peut être exigée pour éviter la usurpation.',
    'Conservation : les données sont conservées pendant la durée de votre compte et un délai raisonnable ensuite pour obligations légales, preuve en cas de litige ou réclamation, puis supprimées ou anonymisées lorsque plus nécessaires.',
    'Sécurité : des mesures techniques et organisationnelles raisonnables sont mises en œuvre pour protéger les données contre la perte, l’accès non autorisé ou la divulgation. Aucun système n’étant infaillible, l’utilisateur est invité à choisir un mot de passe robuste et à ne pas partager ses identifiants.',
    'Mineurs : le Service s’adresse à des professionnels ; il n’est pas destiné aux mineurs. Si des données de mineurs étaient recueillies par erreur, elles seront supprimées dès notification.',
    'Modifications : le présent avis peut être mis à jour pour refléter l’évolution du Service ou des exigences légales. La date de mise à jour peut être indiquée dans l’interface ; l’usage continu du Service après modification vaut prise de connaissance, sauf lorsque le consentement est à nouveau requis par la loi.',
  ],
  es: [
    'El presente aviso describe cómo se tratan los datos personales recabados a través de este directorio profesional en línea (en adelante, el « Servicio »), operado desde el territorio mexicano. Se elabora tomando en cuenta la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) y los principios de licitud, consentimiento, información, finalidad, lealtad, proporcionalidad y responsabilidad.',
    'Responsable del tratamiento: NextStep Services (o la entidad designada como operadora del Servicio), como responsable de los datos personales tratados en el marco del directorio de negocios francófonos de Guadalajara. Para cualquier consulta sobre este documento o sobre sus derechos, puede usar los datos de contacto indicados mediante el enlace de contacto al pie de página.',
    'Datos recabados: identidad (nombre, apellidos), datos de contacto profesional (correo, teléfono, mensajería si los proporciona), datos relativos a la empresa (razón social, sector, número de empleados, ubicación, sitio web, necesidades o intereses profesionales que usted indique), contenidos que publique (perfil, anuncios de oportunidades, comentarios en su caso), datos de acceso y seguridad (identificador de cuenta, registros técnicos necesarios para la autenticación y la prevención de abusos), y cualquier otra información que decida proporcionar voluntariamente en los formularios.',
    'Finalidades: (1) crear y mostrar su ficha en el directorio según la visibilidad que defina; (2) permitir el contacto entre miembros; (3) asegurar el funcionamiento técnico del Servicio (alojamiento, respaldo, estadísticas de uso agregadas); (4) enviar comunicaciones relacionadas con la cuenta o el Servicio cuando sea necesario; (5) cumplir obligaciones legales aplicables en México; (6) moderar contenidos y prevenir fraude o usos ilícitos.',
    'Transferencias y encargados: el Servicio puede utilizar proveedores (alojamiento, autenticación, base de datos, mensajería) ubicados en México o en el extranjero. En ese caso, se buscan cláusulas contractuales o mecanismos reconocidos para proteger sus datos conforme a la LFPDPPP. Los datos pueden transitar o almacenarse en servidores fuera de México; usted es informado mediante el presente aviso.',
    'Base del tratamiento: su consentimiento al registrarse o actualizar su perfil, la ejecución de medidas precontractuales o del contrato de prestación del Servicio, y el cumplimiento de obligaciones legales cuando corresponda. Los campos obligatorios son necesarios para prestar el Servicio; los opcionales se basan en su consentimiento.',
    'Derechos de los titulares (ARCO y otros): de conformidad con la LFPDPPP, puede acceder, rectificar, cancelar u oponerse al tratamiento de sus datos, o revocar su consentimiento para los tratamientos que lo requieran, en los términos y plazos que establece la ley. También puede limitar el uso o divulgación de sus datos cuando la ley lo permita. Las solicitudes pueden enviarse por el canal de contacto indicado al pie de página; puede solicitarse identificación para evitar suplantación.',
    'Conservación: los datos se conservan mientras exista su cuenta y un plazo razonable después para obligaciones legales, prueba en caso de controversia o reclamación, y luego se eliminan o anonimizan cuando ya no sean necesarios.',
    'Seguridad: se aplican medidas técnicas y organizativas razonables para proteger los datos frente a pérdida, acceso no autorizado o divulgación. Ningún sistema es infalible; se le invita a usar una contraseña segura y a no compartir sus credenciales.',
    'Menores: el Servicio está dirigido a profesionales; no está destinado a menores. Si por error se recabaran datos de menores, se eliminarán tras la notificación correspondiente.',
    'Modificaciones: el presente aviso puede actualizarse para reflejar cambios en el Servicio o en los requisitos legales. La fecha de actualización puede indicarse en la interfaz; el uso continuado del Servicio después de un cambio implica conocimiento del mismo, salvo cuando la ley exija un nuevo consentimiento.',
  ],
  en: [
    'This notice describes how personal data collected through this online professional directory (the “Service”), operated from Mexico, are processed. It reflects the Federal Law on Protection of Personal Data Held by Private Parties (LFPDPPP) and the principles of lawfulness, consent, information, purpose, loyalty, proportionality and accountability.',
    'Data controller: NextStep Services (or the entity designated as operator of the Service), as controller of personal data processed for the French-speaking business directory in Guadalajara. For questions about this notice or your rights, use the contact details provided via the “Contact” link in the footer.',
    'Data collected: identity (name), professional contact details (email, phone, messaging if provided), company-related data (company name, sector, headcount, location, website, professional needs or interests as you enter them), content you publish (profile, opportunity posts, comments if any), login and security data (account identifier, technical logs required for authentication and abuse prevention), and any other information you voluntarily provide in forms.',
    'Purposes: (1) create and display your directory profile according to visibility settings you choose; (2) enable networking between members; (3) operate the Service technically (hosting, backup, aggregated usage statistics); (4) send account- or Service-related communications when necessary; (5) comply with legal obligations applicable in Mexico; (6) moderate content and prevent fraud or unlawful use.',
    'Transfers and processors: the Service may use providers (hosting, authentication, database, messaging) located in Mexico or abroad. Contractual clauses or recognised safeguards aim to protect your data in line with the LFPDPPP. Data may be processed on servers outside Mexico; you are informed by this notice.',
    'Legal basis: your consent when registering or updating your profile, performance of pre-contractual measures or of the Service agreement, and compliance with legal obligations where applicable. Required fields are necessary to provide the Service; optional fields rely on your consent.',
    'Data subject rights (ARCO and others): under the LFPDPPP you may access, rectify, cancel or object to processing of your data, or revoke consent where required by law, within the procedures and time limits set by law. You may also limit use or disclosure of your data where permitted. Requests may be submitted through the “Contact” channel; proof of identity may be required to prevent impersonation.',
    'Retention: data are kept for the life of your account and a reasonable period thereafter for legal obligations, evidence in disputes or claims, then deleted or anonymised when no longer needed.',
    'Security: reasonable technical and organisational measures are applied to protect data against loss, unauthorised access or disclosure. No system is perfect; you are encouraged to use a strong password and not share credentials.',
    'Minors: the Service is aimed at professionals and is not intended for minors. If data from minors were collected by mistake, they will be deleted upon notice.',
    'Changes: this notice may be updated to reflect changes to the Service or legal requirements. An update date may be shown in the interface; continued use after changes constitutes acknowledgement unless the law requires fresh consent.',
  ],
};

export const LEGAL_TERMS_PARAGRAPHS: Record<Language, readonly string[]> = {
  fr: [
    'Les présentes conditions d’utilisation (ci-après les « Conditions ») régissent l’accès et l’usage du Service d’annuaire professionnel en ligne visant la communauté d’affaires francophone à Guadalajara et en région. En créant un compte ou en utilisant le Service, vous acceptez sans réserve les présentes Conditions, dans la mesure permise par le droit mexicain applicable.',
    'Nature du Service : il s’agit d’une plateforme de mise en relation et d’information à vocation professionnelle (B2B / réseau). Le Service ne constitue pas un conseil juridique, fiscal, financier ou commercial ; les échanges entre utilisateurs relèvent de leur seule responsabilité.',
    'Compte utilisateur : vous vous engagez à fournir des informations exactes, à jour et non trompeuses, et à maintenir la confidentialité de vos identifiants. Toute activité réalisée depuis votre compte est présumée effectuée par vous. Vous devez notifier sans délai toute utilisation non autorisée.',
    'Contenus et conduite : vous demeurez propriétaire des contenus que vous publiez, tout en concédant au exploitant une licence non exclusive, mondiale et gratuite, strictement limitée à l’hébergement, l’affichage et la promotion du Service. Il est interdit de publier des contenus illicites, diffamatoires, haineux, violents, obscènes au sens du droit applicable, ou portant atteinte aux droits de tiers. L’exploitant peut retirer tout contenu et suspendre ou clôturer un compte en cas de manquement grave ou répété, ou sur demande des autorités compétentes.',
    'Modération et validation : certaines fiches ou publications peuvent être soumises à validation par l’équipe avant diffusion publique. Cette modération vise la qualité de l’annuaire et le respect des présentes Conditions ; elle ne garantit pas l’exactitude des informations fournies par les utilisateurs.',
    'Propriété intellectuelle : la structure du site, les marques, logos et éléments graphiques du Service (hors contenus utilisateurs) demeurent la propriété de leurs titulaires. Toute reproduction non autorisée est interdite.',
    'Disponibilité : le Service est fourni « en l’état ». L’exploitant s’efforce d’assurer une disponibilité raisonnable mais ne garantit pas l’absence d’interruptions, d’erreurs ou de pertes de données ; une maintenance peut être réalisée sans préavis dans des limites raisonnables.',
    'Limitation de responsabilité : dans les limites autorisées par le droit mexicain (notamment le Código Civil federal et, le cas échéant, la loi fédérale sur la protection du consommateur pour les relations couvertes), l’exploitant ne saurait être tenu responsable des dommages indirects, perte de profits, perte de données ou préjudices résultant de l’usage du Service ou des relations entre utilisateurs. La responsabilité totale de l’exploitant, si elle est reconnue, pourra être limitée au montant payé par l’utilisateur au cours des douze (12) mois précédant le fait générateur, ou à zéro si le Service est gratuit.',
    'Indemnisation : vous vous engagez à garantir l’exploitant contre toute réclamation de tiers résultant de votre usage du Service ou de vos contenus, dans la mesure permise par la loi.',
    'Liens externes : le Service peut contenir des liens vers des sites tiers ; l’exploitant n’en contrôle pas le contenu et décline toute responsabilité à leur égard.',
    'Modifications : les Conditions peuvent être mises à jour ; la version applicable est celle publiée sur le Service. L’usage continu après notification ou publication des modifications vaut acceptation, sauf disposition impérative contraire.',
    'Droit applicable et juridiction : les présentes Conditions sont régies en substance par les lois fédérales des États-Unis mexicains. Les tribunaux compétents du ressort de l’exploitant au Mexique seront seuls compétents pour tout litige, sous réserve des règles d’ordre public applicables aux consommateurs le cas échéant.',
    'Contact : pour toute question relative aux présentes Conditions, utilisez le lien « Contact » en pied de page.',
  ],
  es: [
    'Los presentes términos de uso (en adelante, los « Términos ») rigen el acceso y el uso del Servicio de directorio profesional en línea dirigido a la comunidad de negocios francófona en Guadalajara y la región. Al crear una cuenta o usar el Servicio, usted acepta sin reserva los presentes Términos, en la medida permitida por la legislación mexicana aplicable.',
    'Naturaleza del Servicio: es una plataforma de contacto e información de carácter profesional (B2B / red). El Servicio no constituye asesoría legal, fiscal, financiera o comercial; las relaciones entre usuarios son de su exclusiva responsabilidad.',
    'Cuenta de usuario: se compromete a proporcionar datos exactos, actualizados y no engañosos, y a mantener la confidencialidad de sus credenciales. Toda actividad realizada desde su cuenta se presume realizada por usted. Debe notificar de inmediato cualquier uso no autorizado.',
    'Contenidos y conducta: usted conserva la propiedad de los contenidos que publica, otorgando al operador una licencia no exclusiva, mundial y gratuita, estrictamente limitada al alojamiento, la visualización y la promoción del Servicio. Queda prohibido publicar contenidos ilícitos, difamatorios, de odio, violentos, obscenos según el derecho aplicable, o que vulneren derechos de terceros. El operador puede retirar contenidos y suspender o cerrar cuentas ante incumplimientos graves o reiterados, o a requerimiento de autoridades competentes.',
    'Moderación y validación: ciertos perfiles o publicaciones pueden someterse a validación del equipo antes de su difusión pública. Esta moderación busca la calidad del directorio y el respeto a los Términos; no garantiza la exactitud de la información proporcionada por los usuarios.',
    'Propiedad intelectual: la estructura del sitio, marcas, logotipos y elementos gráficos del Servicio (distintos de los contenidos de usuarios) son propiedad de sus titulares. Queda prohibida la reproducción no autorizada.',
    'Disponibilidad: el Servicio se ofrece « tal cual ». El operador procura una disponibilidad razonable pero no garantiza la ausencia de interrupciones, errores o pérdida de datos; puede realizarse mantenimiento sin previo aviso dentro de límites razonables.',
    'Limitación de responsabilidad: en los límites permitidos por el derecho mexicano (incluido el Código Civil federal y, en su caso, la Ley Federal de Protección al Consumidor para las relaciones cubiertas), el operador no será responsable de daños indirectos, lucro cesante, pérdida de datos o perjuicios derivados del uso del Servicio o de las relaciones entre usuarios. La responsabilidad total del operador, si se reconoce, podrá limitarse al monto pagado por el usuario en los doce (12) meses anteriores al hecho generador, o a cero si el Servicio es gratuito.',
    'Indemnización: usted se obliga a mantener indemne al operador frente a reclamaciones de terceros derivadas de su uso del Servicio o de sus contenidos, en la medida permitida por la ley.',
    'Enlaces externos: el Servicio puede incluir enlaces a sitios de terceros; el operador no controla su contenido y declina responsabilidad al respecto.',
    'Modificaciones: los Términos pueden actualizarse; la versión aplicable es la publicada en el Servicio. El uso continuado tras la notificación o publicación de cambios implica aceptación, salvo norma imperativa en contrario.',
    'Legislación y jurisdicción aplicables: los presentes Términos se rigen sustancialmente por las leyes federales de los Estados Unidos Mexicanos. Los tribunales competentes del domicilio del operador en México serán exclusivos para cualquier controversia, sin perjuicio de las reglas de orden público aplicables a consumidores en su caso.',
    'Contacto: para cualquier consulta sobre los presentes Términos, utilice el enlace de contacto al pie de página.',
  ],
  en: [
    'These terms of use (the “Terms”) govern access to and use of the online professional directory service for the French-speaking business community in Guadalajara and the region. By creating an account or using the Service, you accept these Terms without reservation, to the extent permitted by applicable Mexican law.',
    'Nature of the Service: it is a professional networking and information platform (B2B / community). The Service does not provide legal, tax, financial or commercial advice; dealings between users are solely their responsibility.',
    'User account: you agree to provide accurate, up-to-date and non-misleading information and to keep your credentials confidential. Activity under your account is presumed to be yours. You must notify us promptly of any unauthorised use.',
    'Content and conduct: you retain ownership of content you publish, while granting the operator a non-exclusive, worldwide, royalty-free licence strictly limited to hosting, displaying and promoting the Service. You must not publish unlawful, defamatory, hateful, violent or obscene content under applicable law, or content that infringes third-party rights. The operator may remove content and suspend or close accounts for serious or repeated breaches, or when required by competent authorities.',
    'Moderation and validation: some profiles or posts may be reviewed before public display. This aims to maintain directory quality and compliance with the Terms; it does not guarantee accuracy of user-supplied information.',
    'Intellectual property: site structure, trademarks, logos and Service graphics (excluding user content) remain property of their owners. Unauthorised reproduction is prohibited.',
    'Availability: the Service is provided “as is”. The operator seeks reasonable availability but does not guarantee uninterrupted, error-free operation or absence of data loss; maintenance may occur without prior notice within reasonable bounds.',
    'Limitation of liability: to the fullest extent permitted by Mexican law (including the Federal Civil Code and, where applicable, the Federal Consumer Protection Law for covered relationships), the operator is not liable for indirect damages, lost profits, data loss or harm arising from use of the Service or interactions between users. Total liability of the operator, if any, may be limited to amounts paid by the user in the twelve (12) months before the event giving rise to liability, or zero if the Service is free.',
    'Indemnity: you agree to indemnify the operator against third-party claims arising from your use of the Service or your content, to the extent permitted by law.',
    'External links: the Service may link to third-party sites; the operator does not control their content and disclaims liability.',
    'Changes: the Terms may be updated; the version published on the Service applies. Continued use after notice or publication of changes constitutes acceptance, except where mandatory law requires otherwise.',
    'Governing law and jurisdiction: these Terms are governed in substance by the federal laws of the United Mexican States. Courts at the operator’s place of business in Mexico shall have exclusive jurisdiction, subject to mandatory consumer-protection rules where applicable.',
    'Contact: for questions about these Terms, use the “Contact” link in the footer.',
  ],
};
