/**
 * Chaînes EN de référence pour la colonne annuaire (recherche + compteur).
 * Référence EN pour alignement avec `src/i18n/en.ts` (clés proches de `TRANSLATIONS`).
 */
export const DIRECTORY_SIDEBAR_COPY_EN = {
  searchBlockTitle: 'Search the directory',
  searchDirectoryPlaceholder: 'Search a member, company, or need…',
  searchButton: 'Search',
  filterSectorLabel: 'Sector',
  filterSectorDefault: 'Sector',
  filterTypeLabel: 'Profile type',
  filterTypeDefault: 'Profile',
  filterTypeCompany: 'Company',
  filterTypeMember: 'Member',
  filterLocationLabel: 'Location',
  filterLocationDefault: 'Location',
  filterLocationCentro: 'Guadalajara Centre',
  filterLocationZapopan: 'Zapopan',
  filterLocationProvidencia: 'Providencia',
  filterLocationOther: 'Other',
  clearFilters: 'Clear filters',
  randomProfile: '🎲 Discover a random profile',
  randomProfileEmpty: 'No profile available',
  opportunitiesEmpty: 'No opportunities at the moment.',
  launchTitle: 'Community launching now',
  launchSubtitle: 'Be among the first French-speaking members in Guadalajara.',
  launchCta: 'Create my profile now →',
  statsMembers: 'members',
  statsSectors: 'sectors',
  statsOpportunities: 'opportunities',
  dashboardTab: 'Dashboard',
  radarTitle: 'Network radar',
  radarSubtitle:
    'Real-time data on the needs and activity of the French-speaking business community in Guadalajara.',
  radarLive: 'Updated in real time',
  kpiMembers: 'Members',
  kpiNeeds: 'Needs',
  kpiSectors: 'Sectors',
  kpiOpportunities: 'Opportunities',
  chartSectorsTitle: 'Sectors represented',
  chartSectorsEmpty: 'The chart will grow as new members join.',
  chartNeedsTitle: 'Top network needs',
  chartPassionsTitle: 'Network passions',
  chartPassionsEmpty: 'No passions listed yet.',
  chartCenter: 'members',
  radarRecentOpportunitiesTitle: 'Recent opportunities',
  radarRecentOpportunitiesEmpty: 'No opportunities at the moment.',
  radarLockedMessage:
    'Radar data is available after you sign up: sign in and save your directory profile to view stats and use interactions.',
  radarLockedCtaGuest: 'Sign in or register',
  radarLockedCtaProfile: 'Complete my directory profile',
  vueTitle: 'Community overview',
  vueSubtitle:
    'Who is in the community: sectors, company sizes, seniority, statuses.',
  cardMembersBySector: 'Members by sector',
  cardMembersBySize: 'Members by company size',
  cardMembersBySeniority: 'Seniority in Guadalajara',
  cardMembersByStatus: 'Member status',
  kpiTopSector: 'Top sector',
  kpiTopSize: 'Dominant size',
  kpiGDLMedianYears: 'Median seniority',
  kpiTopStatus: 'Dominant status',
  needsTitle: 'Network needs',
  needsSubtitle:
    'Understand business needs expressed by members by sector and over time.',
  cardTopNeeds: 'Top needs',
  cardNeedsHeatmap: 'Needs by sector',
  cardNeedsTimeseries: 'Monthly evolution of needs',
  filterNeedSector: 'Filter by sector',
  filterNeedSize: 'Filter by company size',
  need_sourcing: 'Sourcing',
  need_partners: 'Partners',
  need_recruitment: 'Recruitment',
  need_visibility: 'Visibility',
  need_softlanding: 'Soft‑landing',
  need_legal: 'Legal/tax advice',
  tagNewMember: 'New',
  tagUrgentNeed: 'Urgent need',
  tagsMore: '+{{count}} more',
  tagsCollapse: 'Show less',
} as const;
